### PR TITLE
Slight simplifications to text format

### PR DESCRIPTION
**Pull request by rossberg**
As previously suggested:

* Drop `passive` keyword (no longer needed for disambiguation).
* Remove special case syntax for passive funcref segments (would not work for other element types).

### CODE REVIEW

**Comment by binji** [comment]
@lars-t-hansen for changes to the text format

I'm OK w/ this change in general, though I'm curious your thoughts about the generated tests here. Personally, I'd prefer either making the change in the JS source, or removing the generators entirely. Since the tests are so verbose, I'm hesitant to suggest we modify them by hand from now on.

**Comment by rossberg** [comment]
Good point. Personally, I am not convinced it's worthwhile to maintain a dependency on the entire node ecosystem for a handful of generated tests. Also, it's more difficult to add simple tests that way.

**Comment by lars-t-hansen** [comment]
Yeah, no objections, except SpiderMonkey's syntax is drifting further and further away from the official syntax... :-/

**Comment by rossberg** [comment]
Should I remove the generators then (probably incorporating some of the comments into the tests)?

**Comment by rossberg** [comment]
Friendly ping.

**Comment by binji** [comment]
Yeah, I'm OK w/ removing the generators. We already have tests that are like this (e.g. `f32.wast`, `skip-stack-guard-page.wast`) and those don't seem to have been too much of an issue.

**Comment by rossberg** [comment]
Okay, done.

**Comment by binji** [comment]
Oops, just noticed PR #86. I'll try to merge these two.

**Pull request merged**
