### PR TITLE
Add memory index for {memory,table}.init

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by binji** [comment]
I noticed this when reviewing https://github.com/WebAssembly/bulk-memory-operations/pull/32.

**Comment by alexcrichton** [comment]
Is the memory index required for `memory.drop`? That's just dropping a data segment which otherwise isn't associated with a memory, right? (in that you can only drop a passive segment which doesn't have an associated memory index with it)

**Comment by rossberg** [comment]
Agreeing with @alexcrichton that memory/table.drop don't need a memindex.

**Comment by binji** [comment]
Oops, right :-)

**Pull request merged**
